export type Styles =
  | 'Solitaire'
  | 'Halo'
  | 'Cluster'
  | 'Three Stone'
  | 'Five Stone'
  | 'Trilogy'
  | 'Other'
  | 'BRACELET'
  | 'EARRING'
  | 'PENDANT'
  | 'DRESS RING'
  | 'FULL SET'
  | 'HALF SET'
  | 'Shaped'
  | 'Plains'
  | 'Patterns'
  | 'Ceramic'
  | 'Diamond'
  | 'Two Colour'
